spring:
    application:
        name: accounts-microservice
    datasource:
    # endpoint of h2 database
        url: jdbc:h2:mem:accountsdb
        username: root
        password: password

    # enables h2 database
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
        # to automatically create tables from sql commands on startup
            ddl-auto:  update
        # to show sql queries in console executed by jpa against h2
        show-sql: true




server:
    port: 8080



